import java.awt.Frame;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
public class clear extends javax.swing.JFrame{
      Connection cn;
      PreparedStatement ps;
      ResultSet res;
    /**
     * Creates new form login
     */
    public clear(){
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        usernamee = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        clearmsg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        stat = new javax.swing.JButton();
        check = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        stud_logout = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lib = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        magic = new javax.swing.JPanel();
        magix = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        magictable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setBackground(new java.awt.Color(102, 102, 0));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\minilogo.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 90));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 70)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\darkgreen.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1290, 10));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\icon.png")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -80, -1, 200));

        usernamee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(usernamee, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        id.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        msg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        msg.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        clearmsg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(clearmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Student ID :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Student Name :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Remarks :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 70)); // NOI18N
        jLabel1.setText("NEU Library");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 390, 80));

        stat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stat.setText("BORROWING");
        stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statActionPerformed(evt);
            }
        });
        getContentPane().add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 50));

        check.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\whitebg.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 100));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\LMS\\src\\whitebg.png")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 880, 400));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setText("Student Library Clearance");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clear.setText("CLEARANCE");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, 50));

        stud_logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stud_logout.setText("LOGOUT");
        stud_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(stud_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 50));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("BOOK MONITOR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 170, 50));

        lib.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lib.setText("THE LIBRARY");
        lib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libActionPerformed(evt);
            }
        });
        getContentPane().add(lib, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 50));

        home.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\greenbg.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 640));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\lightgreen.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1400, 690));

        magix.setText("jLabel14");
        magic.add(magix);

        magictable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "loginno", "username"
            }
        ));
        jScrollPane1.setViewportView(magictable);

        magic.add(jScrollPane1);

        getContentPane().add(magic, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()|Frame.MAXIMIZED_BOTH);
        fetchh();
        magic.setVisible(false);
        TableModel model = magictable.getModel();
            int selectedRowIndex = magictable.getSelectedRow();
            magix.setText(model.getValueAt(0, 1).toString());
        
            
        Function f = new Function();
        ResultSet res = null;
        res = f.find(magix.getText());
        try{
            if(res.next()){
                id.setText(res.getString("id"));
                String lname = (res.getString("lastname"));
                String fname = (res.getString("firstname"));
                String mname = (res.getString("middlename"));
                String full = lname + ", " +fname + " "+ mname;
                usernamee.setText(full);
                clearmsg.setText(res.getString("status"));
                msg.setText(res.getString("message"));
        }
        }
        catch(Exception e){
        }
        if(clearmsg.getText().equals("You have unreturned book(s)")){
            check.setText("Please check Book Monitor for details");
        }
     
    }//GEN-LAST:event_formWindowOpened

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        stud a = new stud();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void libActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libActionPerformed
        lib_main a = new lib_main();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_libActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        studmonitor a = new studmonitor();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void stud_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_logoutActionPerformed
        stud_login a = new stud_login();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_stud_logoutActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clear a = new clear();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_clearActionPerformed

    private void statActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statActionPerformed
        status a = new status();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_statActionPerformed
    public void fetchh(){
        try{
            cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            String q = "Select loginno as 'Login No' , username as 'username' from studentlogin order by loginno desc";
            ps = cn.prepareStatement(q);
            res=ps.executeQuery();
            magictable.setModel(DbUtils.resultSetToTableModel(res));
        } 
        catch(Exception e){
        }
    }
    public class Function{
        Connection cn = null;
        ResultSet res = null;
        PreparedStatement ps = null;
        public ResultSet find(String s){
            try{
                cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
                ps = cn.prepareStatement("Select * from clearance where username = ?");
                ps.setString(1, s);
                res = ps.executeQuery();
                }      
                catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            return res;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel check;
    private javax.swing.JButton clear;
    private javax.swing.JLabel clearmsg;
    private javax.swing.JButton home;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lib;
    private javax.swing.JPanel magic;
    private javax.swing.JTable magictable;
    private javax.swing.JLabel magix;
    private javax.swing.JLabel msg;
    private javax.swing.JButton stat;
    private javax.swing.JButton stud_logout;
    private javax.swing.JLabel usernamee;
    // End of variables declaration//GEN-END:variables
}
