import java.awt.Frame;
import java.sql.*;
import java.util.Calendar;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class delete extends javax.swing.JFrame{
      Connection cn;
      PreparedStatement ps;
      ResultSet res;
      String sort;
    /**
     * Creates new form login
     */
    public delete(){
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jButton2 = new javax.swing.JButton();
        admin_addbtn = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin_delbtn = new javax.swing.JButton();
        admin_masterbtn = new javax.swing.JButton();
        del = new javax.swing.JButton();
        s = new javax.swing.JButton();
        c = new javax.swing.JButton();
        b = new javax.swing.JButton();
        admin_reqbtn4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        masterlist = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        admin_deltitle = new javax.swing.JLabel();
        admin_delsubtitle = new javax.swing.JLabel();
        admin_delauthor = new javax.swing.JLabel();
        admin_dellang = new javax.swing.JLabel();
        admin_delbookno = new javax.swing.JLabel();
        admin_delpub = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        admin_delreason = new javax.swing.JTextArea();
        admin_delsearchtext = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        sortby = new javax.swing.JComboBox();
        delsearch = new javax.swing.JButton();
        admin_editcancel = new javax.swing.JButton();
        admin_delete = new javax.swing.JButton();
        bookno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setBackground(new java.awt.Color(102, 102, 0));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 110, 30));

        admin_addbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_addbtn.setText("ADD BOOK");
        admin_addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, 50));

        home.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 50));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrator Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 630, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\admintitle.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 110));

        admin_delbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_delbtn.setText("EDIT BOOK");
        admin_delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_delbtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_delbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, 50));

        admin_masterbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_masterbtn.setText("MASTERLIST");
        admin_masterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_masterbtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_masterbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 170, 50));

        del.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        del.setText("DELETE BOOK");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 170, 50));

        s.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        s.setText("STUDENT INFO");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 170, 50));

        c.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        c.setText("COUNTER");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 170, 50));

        b.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        b.setText("BOOK MONITOR");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 170, 50));

        admin_reqbtn4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_reqbtn4.setText("REQUESTS");
        admin_reqbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_reqbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(admin_reqbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 170, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masterlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookNo", "Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masterlist.setGridColor(new java.awt.Color(255, 255, 255));
        masterlist.setShowHorizontalLines(false);
        masterlist.setShowVerticalLines(false);
        masterlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(masterlist);
        if (masterlist.getColumnModel().getColumnCount() > 0) {
            masterlist.getColumnModel().getColumn(0).setResizable(false);
            masterlist.getColumnModel().getColumn(0).setPreferredWidth(70);
            masterlist.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 400, 220));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("TITLE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("LANGUAGE:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("PUBLISHER:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("SUBTITLE:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("AUTHOR:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("BOOKNO:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Sort by");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Please state here reason for deleting:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));
        jPanel1.add(admin_deltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));
        jPanel1.add(admin_delsubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));
        jPanel1.add(admin_delauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));
        jPanel1.add(admin_dellang, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, -1, -1));
        jPanel1.add(admin_delbookno, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));
        jPanel1.add(admin_delpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Click here                           to view DELETED BOOK(s)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("REASON:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        jButton1.setText("DELETED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 90, 40));

        admin_delreason.setColumns(20);
        admin_delreason.setRows(5);
        jScrollPane2.setViewportView(admin_delreason);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 300, -1));
        jPanel1.add(admin_delsearchtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 100, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("ENTER BOOKNO:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        sortby.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sortby.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TITLE", "BOOKNO" }));
        sortby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortbyActionPerformed(evt);
            }
        });
        jPanel1.add(sortby, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 80, 30));

        delsearch.setText("Search");
        delsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delsearchActionPerformed(evt);
            }
        });
        jPanel1.add(delsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 70, -1));

        admin_editcancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin_editcancel.setText("CANCEL");
        admin_editcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_editcancelActionPerformed(evt);
            }
        });
        jPanel1.add(admin_editcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 110, 50));

        admin_delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin_delete.setText("DELETE");
        admin_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(admin_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 110, 50));

        bookno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(bookno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel6.setText("Delete Book");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\LMS\\src\\whitebg.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 950, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admininnerbg.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1080, 620));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\adminbg.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1300, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()|Frame.MAXIMIZED_BOTH);
        sort = "title";
        fetch();
    }//GEN-LAST:event_formWindowOpened

    private void admin_addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_addbtnActionPerformed
        add a = new add();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_addbtnActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        admin a = new admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void masterlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterlistMouseClicked
        DefaultTableModel model = (DefaultTableModel)masterlist.getModel();
        int selectedRowIndex = masterlist.getSelectedRow();
        
        try{
            admin_delsearchtext.setText(model.getValueAt(selectedRowIndex, 0).toString());
            
            }
        catch(Exception e){
            
        }            
    }//GEN-LAST:event_masterlistMouseClicked
   public class Function{
        Connection cn = null;
        ResultSet res = null;
        PreparedStatement ps = null;
        public ResultSet find(String s){
            try{
                cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
                ps = cn.prepareStatement("Select * from masterlist where booknumber = ?");
                ps.setString(1, s);
                res = ps.executeQuery();
                }      
                catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            return res;
        }
    }
    private void admin_masterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_masterbtnActionPerformed
        masterlist a = new masterlist();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_masterbtnActionPerformed

    private void admin_delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_delbtnActionPerformed
        view a = new view();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_delbtnActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        delete a = new delete();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_delActionPerformed

    private void admin_editcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_editcancelActionPerformed
       admin a = new admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_editcancelActionPerformed

    private void admin_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_deleteActionPerformed
        Calendar calendar = Calendar.getInstance();
        java.sql.Date ourJavaDateObject = new java.sql.Date(calendar.getTime().getTime());
      
        try{
            if(admin_delreason.getText().isEmpty()){
                error.setText("* Please state the reason");
            } else{
                error.setText("");
            }
            if(error.getText().isEmpty()){
            int yesorno = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this book?");
            if(yesorno == JOptionPane.YES_OPTION){
            cn=sql.myConnection();
            String ins="INSERT INTO deleted Values (?,?,?,?,?,?,?,?)";
            ps=cn.prepareStatement(ins);           
            ps.setString(1, admin_delbookno.getText());
            String firstname = admin_deltitle.getText().toString();
            ps.setString(2, firstname);
            String surname = admin_delsubtitle.getText().toString();
            ps.setString(3, surname);
            ps.setString(4, admin_delauthor.getText());
            ps.setString(5, admin_delpub.getText());
            ps.setString(6, admin_dellang.getText());
            ps.setString(7, admin_delreason.getText());
            String s = ourJavaDateObject.toString();
            ps.setString(8, s);
            ps.executeUpdate();
            ps.close();
            }
            
            if(yesorno == JOptionPane.YES_OPTION){
            cn=sql.myConnection();
            String delete="DELETE from masterlist where booknumber = "+admin_delbookno.getText();
            ps=cn.prepareStatement(delete);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Book Deleted!");
            admin_delsearchtext.setText("");
            admin_delbookno.setText("");
            admin_deltitle.setText("");
            admin_delsubtitle.setText("");
            admin_delauthor.setText(" ");
            admin_delpub.setText(" ");
            admin_dellang.setText(" ");
            admin_delreason.setText(" ");

            }
            }
        }
        catch(Exception e){
            

        }
    }//GEN-LAST:event_admin_deleteActionPerformed

    private void sortbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortbyActionPerformed
        if(sortby.getSelectedItem() == "TITLE"){
            sort = "title";
            admin_delsearchtext.setText("");
            bookno.setText("");
            admin_deltitle.setText("");
            admin_delsubtitle.setText("");
            admin_delauthor.setText("");
            admin_delpub.setText("");
            admin_dellang.setText(" ");
        }
        if(sortby.getSelectedItem() == "BOOKNO"){
            admin_delsearchtext.setText("");
            bookno.setText("");
            sort = "booknumber";
            bookno.setText("");
            admin_deltitle.setText("");
            admin_delsubtitle.setText("");
            admin_delauthor.setText("");
            admin_delpub.setText("");
            admin_dellang.setText(" ");
        }
        fetch();
        
    }//GEN-LAST:event_sortbyActionPerformed

    private void delsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delsearchActionPerformed
        Function f = new Function();
        ResultSet res = null;
        res = f.find(admin_delsearchtext.getText());
        try{
            if(res.next()){
                admin_delbookno.setText(res.getString("booknumber"));
                admin_deltitle.setText(res.getString("title"));
                admin_delsubtitle.setText(res.getString("subtitle"));
                admin_delauthor.setText(res.getString("author"));
                admin_delpub.setText(res.getString("publisher"));
                admin_dellang.setText(res.getString("language"));
            }
            else{
                JOptionPane.showMessageDialog(null, "BookNo does not exist.");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_delsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       deleted a = new deleted();
       a.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        admininfo a = new admininfo();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_sActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        counter a = new counter();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_cActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        monitor a = new monitor();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_bActionPerformed

    private void admin_reqbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_reqbtn4ActionPerformed
        adminstatus a = new adminstatus();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_reqbtn4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login a = new login();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void fetch(){
        try{
            cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            String q = "Select booknumber as 'BookNo' , title as 'Title' from masterlist order by " + sort + " asc";
            
            ps = cn.prepareStatement(q);
            res=ps.executeQuery();

            masterlist.setModel(DbUtils.resultSetToTableModel(res));
        } 
        catch(Exception e){
           
        }
    }
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_addbtn;
    private javax.swing.JLabel admin_delauthor;
    private javax.swing.JLabel admin_delbookno;
    private javax.swing.JButton admin_delbtn;
    private javax.swing.JButton admin_delete;
    private javax.swing.JLabel admin_dellang;
    private javax.swing.JLabel admin_delpub;
    private javax.swing.JTextArea admin_delreason;
    private javax.swing.JTextField admin_delsearchtext;
    private javax.swing.JLabel admin_delsubtitle;
    private javax.swing.JLabel admin_deltitle;
    private javax.swing.JButton admin_editcancel;
    private javax.swing.JButton admin_masterbtn;
    private javax.swing.JButton admin_reqbtn4;
    private javax.swing.JButton b;
    private javax.swing.JLabel bookno;
    private javax.swing.JButton c;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JButton del;
    private javax.swing.JButton delsearch;
    private javax.swing.JLabel error;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable masterlist;
    private javax.swing.JButton s;
    private javax.swing.JComboBox sortby;
    // End of variables declaration//GEN-END:variables
}
