import java.awt.Frame;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class deleted extends javax.swing.JFrame{
      Connection cn;
      PreparedStatement ps;
      ResultSet res;
      String sort;
    /**
     * Creates new form login
     */
    public deleted(){
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_homebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        masterlist = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        admin_deldtitle = new javax.swing.JLabel();
        admin_deldsubtitle = new javax.swing.JLabel();
        admin_deldauthor = new javax.swing.JLabel();
        admin_deldpub = new javax.swing.JLabel();
        admin_deldlang = new javax.swing.JLabel();
        admin_deldreason = new javax.swing.JLabel();
        admin_deldbookno = new javax.swing.JLabel();
        sortby = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setBackground(new java.awt.Color(102, 102, 0));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_homebtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_homebtn.setText("BACK");
        admin_homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_homebtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 50));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrator Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 630, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\admintitle.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 110));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masterlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookNo", "Title", "Subtitle", "Author", "Publisher", "Language", "Reason", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masterlist.setEditingRow(0);
        masterlist.setGridColor(new java.awt.Color(255, 255, 255));
        masterlist.setShowHorizontalLines(false);
        masterlist.setShowVerticalLines(false);
        masterlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(masterlist);
        if (masterlist.getColumnModel().getColumnCount() > 0) {
            masterlist.getColumnModel().getColumn(0).setResizable(false);
            masterlist.getColumnModel().getColumn(0).setPreferredWidth(70);
            masterlist.getColumnModel().getColumn(1).setResizable(false);
            masterlist.getColumnModel().getColumn(2).setResizable(false);
            masterlist.getColumnModel().getColumn(3).setResizable(false);
            masterlist.getColumnModel().getColumn(4).setResizable(false);
            masterlist.getColumnModel().getColumn(5).setResizable(false);
            masterlist.getColumnModel().getColumn(6).setResizable(false);
            masterlist.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 980, 290));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("TITLE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("PUBLISHER:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("SUBTITLE:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("AUTHOR:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("BOOKNO:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("View deleted sort by: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("DETAILS:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("LANGUAGE:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("REASON:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));
        jPanel1.add(admin_deldtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));
        jPanel1.add(admin_deldsubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));
        jPanel1.add(admin_deldauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));
        jPanel1.add(admin_deldpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, -1));
        jPanel1.add(admin_deldlang, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, -1));
        jPanel1.add(admin_deldreason, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, -1, -1));
        jPanel1.add(admin_deldbookno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        sortby.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sortby.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TITLE", "BOOKNO" }));
        sortby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortbyActionPerformed(evt);
            }
        });
        jPanel1.add(sortby, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, 30));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel6.setText("Deleted Book Page");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\LMS\\src\\whitebg.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 980, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admininnerbg.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1080, 620));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\adminbg.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1300, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()|Frame.MAXIMIZED_BOTH);
        sort = "title";
        fetch();
        
    }//GEN-LAST:event_formWindowOpened
 
    private void admin_homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_homebtnActionPerformed
        delete a = new delete();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_homebtnActionPerformed

    private void masterlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterlistMouseClicked
     DefaultTableModel model = (DefaultTableModel)masterlist.getModel();
        int selectedRowIndex = masterlist.getSelectedRow();
        
        try{
        admin_deldbookno.setText(model.getValueAt(selectedRowIndex, 0).toString());
        admin_deldtitle.setText(model.getValueAt(selectedRowIndex, 1).toString());
        admin_deldsubtitle.setText(model.getValueAt(selectedRowIndex, 2).toString());
        admin_deldauthor.setText(model.getValueAt(selectedRowIndex, 3).toString());
        admin_deldpub.setText(model.getValueAt(selectedRowIndex, 4).toString());
        admin_deldlang.setText(model.getValueAt(selectedRowIndex, 5).toString());
        admin_deldreason.setText(model.getValueAt(selectedRowIndex, 6).toString());
        
        }
        catch(Exception e){
            
        }
        
      
    }//GEN-LAST:event_masterlistMouseClicked

    private void sortbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortbyActionPerformed
        if(sortby.getSelectedItem() == "TITLE"){
            sort = "title";

        }
        if(sortby.getSelectedItem() == "BOOKNO"){

            sort = "booknumber";
   
        }
        fetch();
        
    }//GEN-LAST:event_sortbyActionPerformed

    public void fetch(){
        try{
            cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            String q = "Select booknumber as 'BookNo' , title as 'Title' , subtitle as 'Subtitle' , author as 'Author' , publisher as 'Publisher' , language as 'Language' , reason as 'Reason' , date as 'Date' from deleted order by " + sort + " asc";
            
            ps = cn.prepareStatement(q);
            res=ps.executeQuery();

            masterlist.setModel(DbUtils.resultSetToTableModel(res));
        } 
        catch(Exception e){
           
        }
    }
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_deldauthor;
    private javax.swing.JLabel admin_deldbookno;
    private javax.swing.JLabel admin_deldlang;
    private javax.swing.JLabel admin_deldpub;
    private javax.swing.JLabel admin_deldreason;
    private javax.swing.JLabel admin_deldsubtitle;
    private javax.swing.JLabel admin_deldtitle;
    private javax.swing.JButton admin_homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable masterlist;
    private javax.swing.JComboBox sortby;
    // End of variables declaration//GEN-END:variables
}
