import java.awt.Frame;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class masterlist extends javax.swing.JFrame{
      Connection cn;
      PreparedStatement ps;
      ResultSet res;
      String sort;
    /**
     * Creates new form login
     */
    public masterlist(){
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        admin_addbtn = new javax.swing.JButton();
        admin_homebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin_delbtn = new javax.swing.JButton();
        admin_editbtn = new javax.swing.JButton();
        c = new javax.swing.JButton();
        b = new javax.swing.JButton();
        s = new javax.swing.JButton();
        master = new javax.swing.JButton();
        admin_reqbtn4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        masterlist = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        errormsg = new javax.swing.JLabel();
        bookno = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        publisher = new javax.swing.JLabel();
        language = new javax.swing.JLabel();
        search_bookno = new javax.swing.JTextField();
        sortby = new javax.swing.JComboBox();
        search = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setBackground(new java.awt.Color(102, 102, 0));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 110, 30));

        admin_addbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_addbtn.setText("ADD BOOK");
        admin_addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, 50));

        admin_homebtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_homebtn.setText("HOME");
        admin_homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_homebtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 50));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrator Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 630, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\admintitle.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 110));

        admin_delbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_delbtn.setText("DELETE BOOK");
        admin_delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_delbtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_delbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 170, 50));

        admin_editbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_editbtn.setText("EDIT BOOK");
        admin_editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_editbtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, 50));

        c.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        c.setText("COUNTER");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 170, 50));

        b.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        b.setText("BOOK MONITOR");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 170, 50));

        s.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        s.setText("STUDENT INFO");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 170, 50));

        master.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        master.setText("MASTERLIST");
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });
        getContentPane().add(master, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 170, 50));

        admin_reqbtn4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_reqbtn4.setText("REQUESTS");
        admin_reqbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_reqbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(admin_reqbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 170, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masterlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookNo", "Title", "Subtitle", "Author", "Publisher", "Language"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masterlist.setDragEnabled(true);
        masterlist.setGridColor(new java.awt.Color(255, 255, 255));
        masterlist.setShowHorizontalLines(false);
        masterlist.setShowVerticalLines(false);
        masterlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(masterlist);
        if (masterlist.getColumnModel().getColumnCount() > 0) {
            masterlist.getColumnModel().getColumn(0).setResizable(false);
            masterlist.getColumnModel().getColumn(0).setPreferredWidth(70);
            masterlist.getColumnModel().getColumn(1).setResizable(false);
            masterlist.getColumnModel().getColumn(2).setResizable(false);
            masterlist.getColumnModel().getColumn(3).setResizable(false);
            masterlist.getColumnModel().getColumn(4).setResizable(false);
            masterlist.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 980, 290));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("TITLE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("LANGUAGE:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("PUBLISHER:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("SUBTITLE:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("AUTHOR:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("BOOKNO:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("View Masterlist sort by: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Enter BookNo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        errormsg.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errormsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        bookno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(bookno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        title.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        title1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        author.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, -1));

        publisher.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, -1, -1));

        language.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(language, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, -1, -1));
        jPanel1.add(search_bookno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 110, -1));

        sortby.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sortby.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TITLE", "BOOKNO" }));
        sortby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortbyActionPerformed(evt);
            }
        });
        jPanel1.add(sortby, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 90, 20));

        search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, 30));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel6.setText("Masterlist");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\LMS\\src\\whitebg.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 980, 530));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admininnerbg.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1080, 620));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\adminbg.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1300, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()|Frame.MAXIMIZED_BOTH);
        fetch();
    }//GEN-LAST:event_formWindowOpened

    private void admin_addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_addbtnActionPerformed
        add a = new add();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_addbtnActionPerformed

    private void admin_homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_homebtnActionPerformed
        admin a = new admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_homebtnActionPerformed

    private void masterlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterlistMouseClicked
         DefaultTableModel model = (DefaultTableModel)masterlist.getModel();
        int selectedRowIndex = masterlist.getSelectedRow();
        
        try{
            search_bookno.setText(model.getValueAt(selectedRowIndex, 0).toString());
            
            }
        catch(Exception e){
            
        }
      
    }//GEN-LAST:event_masterlistMouseClicked
   public class Function{
        Connection cn = null;
        ResultSet res = null;
        PreparedStatement ps = null;
        public ResultSet find(String s){
            try{
                cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
                ps = cn.prepareStatement("Select * from masterlist where booknumber = ?");
                ps.setString(1, s);
                res = ps.executeQuery();
                }      
                catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            return res;
        }
    }
    private void admin_editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_editbtnActionPerformed
        view a = new view();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_editbtnActionPerformed

    private void admin_delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_delbtnActionPerformed
        delete a = new delete();
       a.setVisible(true);
       dispose();
    }//GEN-LAST:event_admin_delbtnActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        counter a = new counter();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_cActionPerformed

    private void sortbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortbyActionPerformed
        if(sortby.getSelectedItem() == "TITLE"){
            sort = "title";

        }
        if(sortby.getSelectedItem() == "BOOKNO"){

            sort = "booknumber";
   
        }
        fetch();
        
    }//GEN-LAST:event_sortbyActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        Function f = new Function();
        ResultSet res = null;
        res = f.find(search_bookno.getText());
        try{
            if(res.next()){
                bookno.setText(res.getString("booknumber"));
                title.setText(res.getString("title"));
                title1.setText(res.getString("subtitle"));
                author.setText(res.getString("author"));
                publisher.setText(res.getString("publisher"));
                language.setText(res.getString("language"));
            }
            else{
                errormsg.setText("*BookNo does not Exist.");
            }
            if(bookno.getText().isEmpty()){
                errormsg.setText("*BookNo does not Exist.");
            }else{
                errormsg.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        monitor a = new monitor();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_bActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        admininfo a = new admininfo();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_sActionPerformed

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        masterlist a = new masterlist();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_masterActionPerformed

    private void admin_reqbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_reqbtn4ActionPerformed
        adminstatus a = new adminstatus();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_reqbtn4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login a = new login();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void fetch(){
        try{
            cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            String q = "Select booknumber as 'BookNo' , title as 'Title' , subtitle as 'Subtitle' , author as 'Author' , publisher as 'Publisher' , language as 'Language' from masterlist order by " + sort + " asc";
            
            ps = cn.prepareStatement(q);
            res=ps.executeQuery();

            masterlist.setModel(DbUtils.resultSetToTableModel(res));
        } 
        catch(Exception e){
           
        }
    }
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_addbtn;
    private javax.swing.JButton admin_delbtn;
    private javax.swing.JButton admin_editbtn;
    private javax.swing.JButton admin_homebtn;
    private javax.swing.JButton admin_reqbtn4;
    private javax.swing.JLabel author;
    private javax.swing.JButton b;
    private javax.swing.JLabel bookno;
    private javax.swing.JButton c;
    private javax.swing.JLabel errormsg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel language;
    private javax.swing.JButton master;
    private javax.swing.JTable masterlist;
    private javax.swing.JLabel publisher;
    private javax.swing.JButton s;
    private javax.swing.JButton search;
    private javax.swing.JTextField search_bookno;
    private javax.swing.JComboBox sortby;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
