import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
public class newuser extends javax.swing.JFrame{
      Connection cn;
      PreparedStatement ps;
      ResultSet res;
    /**
     * Creates new form login
     */
    public newuser(){
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enteruserpw = new javax.swing.JLabel();
        rpassword = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rpwerror = new javax.swing.JLabel();
        pwerrormsg = new javax.swing.JLabel();
        pwerror0 = new javax.swing.JLabel();
        pwerror1 = new javax.swing.JLabel();
        pwerror2 = new javax.swing.JLabel();
        pwerror3 = new javax.swing.JLabel();
        pwerror4 = new javax.swing.JLabel();
        pwerror5 = new javax.swing.JLabel();
        pwerror6 = new javax.swing.JLabel();
        pwerrormsg1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        createaccnt = new javax.swing.JButton();
        day = new javax.swing.JComboBox();
        gender = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        rpasswordtext = new javax.swing.JPasswordField();
        passwordtext = new javax.swing.JPasswordField();
        midname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        usernametext = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        bgpw = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setBackground(new java.awt.Color(102, 102, 0));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enteruserpw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enteruserpw.setText("Enter your username and password");
        getContentPane().add(enteruserpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        rpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rpassword.setText("Re-Enter Password:");
        getContentPane().add(rpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setText("Enter Password:");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Personal Information");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        rpwerror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(rpwerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 10, 20));

        pwerrormsg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pwerrormsg.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pwerrormsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        pwerror0.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pwerror0, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 10, 20));

        pwerror1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pwerror1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 10, 20));

        pwerror2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pwerror2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 10, 20));

        pwerror3.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pwerror3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 10, 20));

        pwerror4.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pwerror4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 10, 20));

        pwerror5.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pwerror5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 10, 20));

        pwerror6.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pwerror6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 10, 20));

        pwerrormsg1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pwerrormsg1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pwerrormsg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("New Era University");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 680, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("NEU Library Management System");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, -1, -1));

        createaccnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createaccnt.setText("Create");
        createaccnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccntActionPerformed(evt);
            }
        });
        getContentPane().add(createaccnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 90, 30));

        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day" }));
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 60, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Male", "Female" }));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 70, -1));

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 70, -1));

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 100, -1));

        rpasswordtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpasswordtextActionPerformed(evt);
            }
        });
        getContentPane().add(rpasswordtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 180, -1));

        passwordtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtextActionPerformed(evt);
            }
        });
        getContentPane().add(passwordtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 180, -1));

        midname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                midnameKeyPressed(evt);
            }
        });
        getContentPane().add(midname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 200, -1));

        lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastnameKeyPressed(evt);
            }
        });
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 200, -1));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 250, -1));

        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactKeyPressed(evt);
            }
        });
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 200, -1));
        getContentPane().add(usernametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 180, -1));

        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstnameKeyTyped(evt);
            }
        });
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 200, -1));

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setText("Username:");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        bgpw.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\LMS\\src\\whitebg.png")); // NOI18N
        getContentPane().add(bgpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 390, 240));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\neucreate.gif")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, 400, 400));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, 30));

        next.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 70, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Gender:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Middle Name:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\greenbg.png")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1370, 80));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Date Of Birth:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Address:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Contact No:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Last Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("First Name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\LMS\\src\\whitebg.png")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 420, 340));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jLabel1.setText("Create New Account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Please Fill up the following information:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\greenbg.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\lightgreen.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1410, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()|Frame.MAXIMIZED_BOTH);
 
    }//GEN-LAST:event_formWindowOpened

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        stud_login a = new stud_login();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtextActionPerformed
      
    }//GEN-LAST:event_passwordtextActionPerformed

    private void rpasswordtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpasswordtextActionPerformed

    }//GEN-LAST:event_rpasswordtextActionPerformed

    private void createaccntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccntActionPerformed

        try{
            String a = String.valueOf(passwordtext.getPassword());
            String b = String.valueOf(rpasswordtext.getPassword());
            
            if(a.equals(b)){
            pwerrormsg.setText("");
            rpwerror.setText("");
            }else {
            pwerrormsg.setText("* Password does not match");
            rpwerror.setText("*");
            }
            
            if(pwerrormsg.getText().isEmpty()){
            cn=sql.myConnection();
            String uname = usernametext.getText().toString();
            String pw = String.valueOf(passwordtext.getPassword());
            String fname = firstname.getText().toString();
            String mname = midname.getText().toString();
            String surname = lastname.getText().toString();
            String g=gender.getSelectedItem().toString();
            String mm=month.getSelectedItem().toString();
            String dd=day.getSelectedItem().toString();
            String yy=year.getSelectedItem().toString();
            String bdate = mm + dd + yy;
            String add = address.getText().toString();
            String con = contact.getText().toString();
            String ins="INSERT INTO student (username, password, firstname, middlename, lastname, gender, birthdate, address, contact) Values ('"+usernametext.getText()+"','"+pw+"','"+fname+"','"+mname+"','"+surname+"','"+g+"','"+bdate+"','"+add+"','"+con+"')";
            ps=cn.prepareStatement(ins);
            ps.executeUpdate(); 
            }
             if(pwerrormsg.getText().isEmpty()){
            cn=sql.myConnection();
            String fname = firstname.getText().toString();
            String mname = midname.getText().toString();
            String surname = lastname.getText().toString();
            String stat = "All books returned";
            String m = " ";
            String que= "INSERT INTO clearance (username, lastname, firstname, middlename, status, message) VALUES ('"+usernametext.getText()+"','"+surname+"','"+fname+"','"+mname+"','"+stat+"','"+m+"')";
            ps=cn.prepareStatement(que);
            ps.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "Successful! Go to Login?");
                stud_login c = new stud_login();
                c.setVisible(true);
                dispose();
             }
             
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null,"Username already exist!");
                
                }
 
    }//GEN-LAST:event_createaccntActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
            if(firstname.getText().isEmpty()){
                pwerrormsg1.setText("Please fill up this Information");
                pwerror0.setText("*");
            } else{
                pwerror0.setText("");
            } 
            if(midname.getText().isEmpty()){
                pwerrormsg1.setText("Please fill up this Information");
                pwerror1.setText("*");
            } else{
                pwerror1.setText("");
            }       
            if(lastname.getText().isEmpty()){
                pwerrormsg1.setText("Please fill up this Information");
                pwerror2.setText("*");
            } else{
                pwerror2.setText("");
            }   
             if(gender.getSelectedItem().equals(" ")){
                pwerrormsg1.setText("Please fill up this Information");
                pwerror3.setText("*");
            } else{
                pwerror3.setText("");
            }
            if(month.getSelectedItem().equals("Month")){
                pwerrormsg1.setText("Please fill up this Information");
                pwerror4.setText("*");
            } else{
                pwerror4.setText("");
            }
            if(day.getSelectedItem().equals("Day")){
                pwerrormsg1.setText("Please fill up this Information");
                pwerror4.setText("*");
            } else{
                pwerror4.setText("");
            }
            if(year.getSelectedItem().equals("Year")){
                pwerrormsg1.setText("Please fill up this Information");
                pwerror4.setText("*");
            } else{
                pwerror4.setText("");
            }
            if(address.getText().isEmpty()){
                pwerrormsg1.setText("Please fill up this Information");
                pwerror5.setText("*");
            } else{
                pwerror5.setText("");
            }
            if(contact.getText().isEmpty()){
                pwerrormsg1.setText("Please fill up this Information");
                pwerror6.setText("*");
            } else{
                pwerror6.setText("");
            }
            if(pwerror0.getText().isEmpty() && pwerror1.getText().isEmpty() && pwerror2.getText().isEmpty() && pwerror3.getText().isEmpty() && pwerror4.getText().isEmpty() && pwerror5.getText().isEmpty() && pwerror6.getText().isEmpty()){
                pwerrormsg1.setText("");
            }
    }//GEN-LAST:event_nextActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
         if(month.getSelectedItem()=="January" || month.getSelectedItem()=="March" || month.getSelectedItem()=="May" || month.getSelectedItem()=="July" || month.getSelectedItem()=="August" || month.getSelectedItem()=="October" || month.getSelectedItem()=="December"){
            day.addItem("1");
            day.addItem("2");
            day.addItem("3");
            day.addItem("4");
            day.addItem("5");
            day.addItem("6");
            day.addItem("7");
            day.addItem("8");
            day.addItem("9");
            day.addItem("10");
            day.addItem("11");
            day.addItem("12");
            day.addItem("13");
            day.addItem("14");
            day.addItem("15");
            day.addItem("16");
            day.addItem("17");
            day.addItem("18");
            day.addItem("19");
            day.addItem("20");
            day.addItem("21");
            day.addItem("22");
            day.addItem("23");
            day.addItem("24");
            day.addItem("25");
            day.addItem("26");
            day.addItem("27");
            day.addItem("28");
            day.addItem("29");
            day.addItem("30");
            day.addItem("31");
        } else if(month.getSelectedItem()=="February"){
            day.addItem("1");
            day.addItem("2");
            day.addItem("3");
            day.addItem("4");
            day.addItem("5");
            day.addItem("6");
            day.addItem("7");
            day.addItem("8");
            day.addItem("9");
            day.addItem("10");
            day.addItem("11");
            day.addItem("12");
            day.addItem("13");
            day.addItem("14");
            day.addItem("15");
            day.addItem("16");
            day.addItem("17");
            day.addItem("18");
            day.addItem("19");
            day.addItem("20");
            day.addItem("21");
            day.addItem("22");
            day.addItem("23");
            day.addItem("24");
            day.addItem("25");
            day.addItem("26");
            day.addItem("27");
            day.addItem("28");
        } else if(month.getSelectedItem()=="April" || month.getSelectedItem()=="June" || month.getSelectedItem()=="September" || month.getSelectedItem()=="November"){
            day.addItem("1");
            day.addItem("2");
            day.addItem("3");
            day.addItem("4");
            day.addItem("5");
            day.addItem("6");
            day.addItem("7");
            day.addItem("8");
            day.addItem("9");
            day.addItem("10");
            day.addItem("11");
            day.addItem("12");
            day.addItem("13");
            day.addItem("14");
            day.addItem("15");
            day.addItem("16");
            day.addItem("17");
            day.addItem("18");
            day.addItem("19");
            day.addItem("20");
            day.addItem("21");
            day.addItem("22");
            day.addItem("23");
            day.addItem("24");
            day.addItem("25");
            day.addItem("26");
            day.addItem("27");
            day.addItem("28");
            day.addItem("29");
            day.addItem("30");
        } else {
            day.removeItem("1");
            day.removeItem("2");
            day.removeItem("3");
            day.removeItem("4");
            day.removeItem("5");
            day.removeItem("6");
            day.removeItem("7");
            day.removeItem("8");
            day.removeItem("9");
            day.removeItem("10");
            day.removeItem("11");
            day.removeItem("12");
            day.removeItem("13");
            day.removeItem("14");
            day.removeItem("15");
            day.removeItem("16");
            day.removeItem("17");
            day.removeItem("18");
            day.removeItem("19");
            day.removeItem("20");
            day.removeItem("21");
            day.removeItem("22");
            day.removeItem("23");
            day.removeItem("24");
            day.removeItem("25");
            day.removeItem("26");
            day.removeItem("27");
            day.removeItem("28");
            day.removeItem("29");
            day.removeItem("30");
            day.removeItem("31");
        }
    }//GEN-LAST:event_monthActionPerformed

    private void firstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyPressed
       char c = evt.getKeyChar();
        if(!(Character.isLetter(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
        evt.consume();
        pwerrormsg1.setText("Please fill up this with correct information");
        pwerror0.setText("*");
        }
    }//GEN-LAST:event_firstnameKeyPressed

    private void firstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameKeyTyped

    private void midnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_midnameKeyPressed
       char c = evt.getKeyChar();
        if(!(Character.isLetter(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
        evt.consume();
        pwerrormsg1.setText("Please fill up this with correct information");
        pwerror1.setText("*");
        }
    }//GEN-LAST:event_midnameKeyPressed

    private void lastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameKeyPressed
      char c = evt.getKeyChar();
        if(!(Character.isLetter(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
        evt.consume();
        pwerrormsg1.setText("Please fill up this with correct information");
        pwerror2.setText("*");
        }
    }//GEN-LAST:event_lastnameKeyPressed

    private void contactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyPressed
       char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
        evt.consume();
        pwerrormsg1.setText("Please fill up this with correct information");
        pwerror6.setText("*");
        }
    }//GEN-LAST:event_contactKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel bgpw;
    private javax.swing.JTextField contact;
    private javax.swing.JButton createaccnt;
    private javax.swing.JComboBox day;
    private javax.swing.JLabel enteruserpw;
    private javax.swing.JTextField firstname;
    private javax.swing.JComboBox gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField midname;
    private javax.swing.JComboBox month;
    private javax.swing.JButton next;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordtext;
    private javax.swing.JLabel pwerror0;
    private javax.swing.JLabel pwerror1;
    private javax.swing.JLabel pwerror2;
    private javax.swing.JLabel pwerror3;
    private javax.swing.JLabel pwerror4;
    private javax.swing.JLabel pwerror5;
    private javax.swing.JLabel pwerror6;
    private javax.swing.JLabel pwerrormsg;
    private javax.swing.JLabel pwerrormsg1;
    private javax.swing.JLabel rpassword;
    private javax.swing.JPasswordField rpasswordtext;
    private javax.swing.JLabel rpwerror;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernametext;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
