import java.awt.Frame;
import java.sql.*;
import java.util.Calendar;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
public class studauthor extends javax.swing.JFrame{
      Connection cn;
      PreparedStatement ps;
      ResultSet res;
      String firstletter ="";
    /**
     * Creates new form login
     */
    public studauthor(){
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stud_liba2 = new javax.swing.JButton();
        stud_liba3 = new javax.swing.JButton();
        stud_liba4 = new javax.swing.JButton();
        stud_liba5 = new javax.swing.JButton();
        stud_liba6 = new javax.swing.JButton();
        stud_liba7 = new javax.swing.JButton();
        stud_liba8 = new javax.swing.JButton();
        stud_liba9 = new javax.swing.JButton();
        stud_liba10 = new javax.swing.JButton();
        stud_liba11 = new javax.swing.JButton();
        stud_liba12 = new javax.swing.JButton();
        stud_liba13 = new javax.swing.JButton();
        stud_liba14 = new javax.swing.JButton();
        stud_liba15 = new javax.swing.JButton();
        stud_liba16 = new javax.swing.JButton();
        stud_liba17 = new javax.swing.JButton();
        stud_liba18 = new javax.swing.JButton();
        stud_liba19 = new javax.swing.JButton();
        stud_liba20 = new javax.swing.JButton();
        stud_liba21 = new javax.swing.JButton();
        stud_liba22 = new javax.swing.JButton();
        stud_liba23 = new javax.swing.JButton();
        stud_liba24 = new javax.swing.JButton();
        stud_liba25 = new javax.swing.JButton();
        stud_liba26 = new javax.swing.JButton();
        stud_liba = new javax.swing.JButton();
        stud_libview = new javax.swing.JButton();
        borrow = new javax.swing.JButton();
        author = new javax.swing.JLabel();
        pub = new javax.swing.JLabel();
        lang = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        stud_title = new javax.swing.JLabel();
        stud_libpub = new javax.swing.JLabel();
        stud_liblang = new javax.swing.JLabel();
        stud_libauthor = new javax.swing.JLabel();
        stud_libsubtitle = new javax.swing.JLabel();
        sub = new javax.swing.JLabel();
        stud_bookno = new javax.swing.JLabel();
        bookno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        library = new javax.swing.JTable();
        text = new javax.swing.JLabel();
        letter = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        stud_logout = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        magic = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        magictable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setBackground(new java.awt.Color(102, 102, 0));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\minilogo.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 90));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 70)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\adminborder.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1290, 10));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 70)); // NOI18N
        jLabel1.setText("NEU Library");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 390, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\whitebg.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 100));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Select one you wish to view");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        stud_liba2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba2.setText("B");
        stud_liba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba2ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, 40));

        stud_liba3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba3.setText("C");
        stud_liba3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba3ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, 40));

        stud_liba4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba4.setText("D");
        stud_liba4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba4ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, 40));

        stud_liba5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba5.setText("E");
        stud_liba5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba5ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, 40));

        stud_liba6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba6.setText("F");
        stud_liba6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba6ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, 40));

        stud_liba7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba7.setText("G");
        stud_liba7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba7ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, 40));

        stud_liba8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba8.setText("H");
        stud_liba8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba8ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, -1, 40));

        stud_liba9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba9.setText("I");
        stud_liba9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba9ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 40, 40));

        stud_liba10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba10.setText("J");
        stud_liba10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba10ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, -1, 40));

        stud_liba11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba11.setText("K");
        stud_liba11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba11ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba11, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, -1, 40));

        stud_liba12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba12.setText("L");
        stud_liba12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba12ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, -1, 40));

        stud_liba13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba13.setText("M");
        stud_liba13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba13ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, -1, 40));

        stud_liba14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba14.setText("N");
        stud_liba14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba14ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 40));

        stud_liba15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba15.setText("O");
        stud_liba15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba15ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, 40));

        stud_liba16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba16.setText("P");
        stud_liba16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba16ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, 40));

        stud_liba17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba17.setText("Q");
        stud_liba17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba17ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, 40));

        stud_liba18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba18.setText("R");
        stud_liba18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba18ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, 40));

        stud_liba19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba19.setText("S");
        stud_liba19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba19ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, 40));

        stud_liba20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba20.setText("T");
        stud_liba20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba20ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba20, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, -1, 40));

        stud_liba21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba21.setText("U");
        stud_liba21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba21ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba21, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, 40));

        stud_liba22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba22.setText("V");
        stud_liba22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba22ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba22, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, -1, 40));

        stud_liba23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba23.setText("W");
        stud_liba23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba23ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba23, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, -1, 40));

        stud_liba24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba24.setText("X");
        stud_liba24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba24ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba24, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, -1, 40));

        stud_liba25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba25.setText("Y");
        stud_liba25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba25ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba25, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, -1, 40));

        stud_liba26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba26.setText("Z");
        stud_liba26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_liba26ActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, -1, 40));

        stud_liba.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_liba.setText("A");
        stud_liba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_libaActionPerformed(evt);
            }
        });
        getContentPane().add(stud_liba, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, 40));

        stud_libview.setText("View Details");
        stud_libview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_libviewActionPerformed(evt);
            }
        });
        getContentPane().add(stud_libview, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, 30));

        borrow.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        borrow.setText("BORROW");
        borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowActionPerformed(evt);
            }
        });
        getContentPane().add(borrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 630, 100, 50));

        author.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        author.setText("AUTHOR:");
        getContentPane().add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, -1, -1));

        pub.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pub.setText("PUBLISHER:");
        getContentPane().add(pub, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, -1, -1));

        lang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lang.setText("LANGUAGE:");
        getContentPane().add(lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, -1));

        title.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        title.setText("TITLE:");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, -1, -1));

        stud_title.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(stud_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        stud_libpub.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(stud_libpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, -1, -1));

        stud_liblang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(stud_liblang, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, -1, -1));

        stud_libauthor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(stud_libauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, -1, -1));

        stud_libsubtitle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(stud_libsubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, -1, -1));

        sub.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sub.setText("SUBTITLE:");
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        stud_bookno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stud_bookno.setText("BOOK NO:");
        getContentPane().add(stud_bookno, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        bookno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(bookno, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, -1));

        library.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book No", "Author"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        library.setShowHorizontalLines(false);
        library.setShowVerticalLines(false);
        library.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libraryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(library);
        if (library.getColumnModel().getColumnCount() > 0) {
            library.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 340, 340));

        text.setText("jLabel10");
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, -1, -1));

        letter.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        getContentPane().add(letter, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("CLEARANCE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, 50));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 630, 100, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\LMS\\src\\whitebg.png")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 1030, 590));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("BORROWING");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 50));

        stud_logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stud_logout.setText("LOGOUT");
        stud_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(stud_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("THE LIBRARY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 50));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("BOOK MONITOR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 170, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\greenbg.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 640));

        magictable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login No", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(magictable);
        if (magictable.getColumnModel().getColumnCount() > 0) {
            magictable.getColumnModel().getColumn(0).setResizable(false);
            magictable.getColumnModel().getColumn(1).setResizable(false);
        }

        magic.add(jScrollPane2);

        getContentPane().add(magic, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 300, 200));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\lightgreen.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1400, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()|Frame.MAXIMIZED_BOTH);
        stud_libview.setVisible(true);
        title.setVisible(true);
        sub.setVisible(true);
        author.setVisible(true);
        pub.setVisible(true);
        lang.setVisible(true);
        stud_bookno.setVisible(true);
        fetchh();
        magic.setVisible(false);
        text.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        stud a = new stud();
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        lib_main a = new lib_main();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void stud_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_logoutActionPerformed
       stud_login a = new stud_login();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_stud_logoutActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void stud_liba10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stud_liba10ActionPerformed

    private void stud_libaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_libaActionPerformed
        letter.setText("A");
        if(letter.getText() == "A"){
        firstletter = "LIKE 'A%'";
        }
        fetch();
    }//GEN-LAST:event_stud_libaActionPerformed

    private void stud_libviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_libviewActionPerformed
        Function f = new Function();
        ResultSet res = null;
        res = f.find(bookno.getText());
        try{
            if(res.next()){
                stud_libsubtitle.setText(res.getString("subtitle"));               
                stud_libauthor.setText(res.getString("author"));               
                stud_libpub.setText(res.getString("publisher"));
                stud_liblang.setText(res.getString("language"));
                
                stud_libsubtitle.setVisible(true);
                stud_libauthor.setVisible(true);
                stud_libpub.setVisible(true);
                stud_liblang.setVisible(true);
                sub.setVisible(true);
                author.setVisible(true);
                pub.setVisible(true);
                lang.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Select one you wish to view details");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_stud_libviewActionPerformed

    private void libraryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libraryMouseClicked
        DefaultTableModel model = (DefaultTableModel)library.getModel();
        int selectedRowIndex = library.getSelectedRow();
        
        try{
            title.setVisible(true);
            stud_bookno.setVisible(true);
            bookno.setText(model.getValueAt(selectedRowIndex, 0).toString());
            stud_title.setText(model.getValueAt(selectedRowIndex, 1).toString());
            stud_libview.setVisible(true);
            
            if(stud_libauthor.isVisible()){
                sub.setVisible(false);
                author.setVisible(false);
                pub.setVisible(false);
                lang.setVisible(false);
                stud_libsubtitle.setVisible(false);
                stud_libauthor.setVisible(false);
                stud_libpub.setVisible(false);
                stud_liblang.setVisible(false);
                
            }

        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_libraryMouseClicked

    private void stud_liba19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba19ActionPerformed
        letter.setText("S");
        if(letter.getText() == "S"){
        firstletter = "LIKE 'S%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba19ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        studmonitor a = new studmonitor();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       status a = new status();
       a.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void borrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowActionPerformed
        Calendar calendar = Calendar.getInstance();
        java.sql.Date ourJavaDateObject = new java.sql.Date(calendar.getTime().getTime());
        
        try{
            int yesorno = JOptionPane.showConfirmDialog(null, "Are you sure you want to borrow this book?");
            if(yesorno == JOptionPane.YES_OPTION){
            TableModel model = magictable.getModel();
            int selectedRowIndex = magictable.getSelectedRow();
            text.setText(model.getValueAt(0, 1).toString());
            }
            if(yesorno == JOptionPane.YES_OPTION){
            cn=sql.myConnection();
            String ins="INSERT INTO borrowlist Values (?,?,?,?,?,?,?)";
            ps=cn.prepareStatement(ins);
            String s = ourJavaDateObject.toString();
            ps.setString(1, s);
            String bkno = bookno.getText().toString();
            ps.setString(2, bkno);
            String tit = stud_title.getText().toString();
            ps.setString(3, tit);
            String auth = stud_libauthor.getText().toString();
            ps.setString(4, auth);
            String user = text.getText().toString();
            ps.setString(5, user);
            String stat= "Pending";
            ps.setString(6, stat);
            String m = " ";
            ps.setString(7, m);
            ps.executeUpdate();
            ps.close();
            JOptionPane.showMessageDialog(null, "Successful!");
            }     
        }
            catch(Exception e){
                    
                    }
    }//GEN-LAST:event_borrowActionPerformed

    private void stud_liba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba2ActionPerformed
        letter.setText("B");
        if(letter.getText() == "B"){
        firstletter = "LIKE 'B%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba2ActionPerformed

    private void stud_liba4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba4ActionPerformed
       letter.setText("D");
        if(letter.getText() == "D"){
        firstletter = "LIKE 'D%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba4ActionPerformed

    private void stud_liba3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba3ActionPerformed
   letter.setText("C");
        if(letter.getText() == "C"){
        firstletter = "LIKE 'C%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba3ActionPerformed

    private void stud_liba5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba5ActionPerformed
         letter.setText("E");
        if(letter.getText() == "E"){
        firstletter = "LIKE 'E%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba5ActionPerformed

    private void stud_liba6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba6ActionPerformed
         letter.setText("F");
        if(letter.getText() == "F"){
        firstletter = "LIKE 'F%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba6ActionPerformed

    private void stud_liba7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba7ActionPerformed
         letter.setText("G");
        if(letter.getText() == "G"){
        firstletter = "LIKE 'G%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba7ActionPerformed

    private void stud_liba8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba8ActionPerformed
         letter.setText("H");
        if(letter.getText() == "H"){
        firstletter = "LIKE 'H%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba8ActionPerformed

    private void stud_liba9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba9ActionPerformed
        letter.setText("I");
        if(letter.getText() == "I"){
        firstletter = "LIKE 'I%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba9ActionPerformed

    private void stud_liba11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba11ActionPerformed
       letter.setText("K");
        if(letter.getText() == "K"){
        firstletter = "LIKE 'K%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba11ActionPerformed

    private void stud_liba12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba12ActionPerformed
        letter.setText("L");
        if(letter.getText() == "L"){
        firstletter = "LIKE 'L%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba12ActionPerformed

    private void stud_liba13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba13ActionPerformed
           letter.setText("M");
        if(letter.getText() == "M"){
        firstletter = "LIKE 'M%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba13ActionPerformed

    private void stud_liba14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba14ActionPerformed
          letter.setText("N");
        if(letter.getText() == "N"){
        firstletter = "LIKE 'N%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba14ActionPerformed

    private void stud_liba15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba15ActionPerformed
        letter.setText("O");
        if(letter.getText() == "O"){
        firstletter = "LIKE 'O%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba15ActionPerformed

    private void stud_liba16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba16ActionPerformed
          letter.setText("P");
        if(letter.getText() == "P"){
        firstletter = "LIKE 'P%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba16ActionPerformed

    private void stud_liba17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba17ActionPerformed
         letter.setText("Q");
        if(letter.getText() == "Q"){
        firstletter = "LIKE 'Q%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba17ActionPerformed

    private void stud_liba18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba18ActionPerformed
      letter.setText("R");
        if(letter.getText() == "R"){
        firstletter = "LIKE 'R%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba18ActionPerformed

    private void stud_liba20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba20ActionPerformed
       letter.setText("T");
        if(letter.getText() == "T"){
        firstletter = "LIKE 'T%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba20ActionPerformed

    private void stud_liba21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba21ActionPerformed
         letter.setText("U");
        if(letter.getText() == "U"){
        firstletter = "LIKE 'U%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba21ActionPerformed

    private void stud_liba22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba22ActionPerformed
        letter.setText("V");
        if(letter.getText() == "V"){
        firstletter = "LIKE 'V%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba22ActionPerformed

    private void stud_liba23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba23ActionPerformed
        letter.setText("W");
        if(letter.getText() == "W"){
        firstletter = "LIKE 'W%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba23ActionPerformed

    private void stud_liba24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba24ActionPerformed
        letter.setText("X");
        if(letter.getText() == "X"){
        firstletter = "LIKE 'X%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba24ActionPerformed

    private void stud_liba25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba25ActionPerformed
         letter.setText("Y");
        if(letter.getText() == "Y"){
        firstletter = "LIKE 'Y%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba25ActionPerformed

    private void stud_liba26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_liba26ActionPerformed
       letter.setText("Z");
        if(letter.getText() == "Z"){
        firstletter = "LIKE 'Z%'";
        }
        fetch();
    }//GEN-LAST:event_stud_liba26ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        lib_main a = new lib_main();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
                                       

    
    public void fetch(){
        try{
            cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            String q = "Select booknumber as 'Book No' , title as 'Title' from masterlist where title "+ firstletter + " order by title asc";
            ps = cn.prepareStatement(q);
            res=ps.executeQuery();
            library.setModel(DbUtils.resultSetToTableModel(res));
        } 
        catch(Exception e){
        }
    }
       public void fetchh(){
        try{
            cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            String q = "Select loginno as 'Login No' , username as 'Username' from studentlogin order by loginno desc";
            ps = cn.prepareStatement(q);
            res=ps.executeQuery();
            magictable.setModel(DbUtils.resultSetToTableModel(res));
        } 
        catch(Exception e){
        }
    }
   
    public class Function{
        Connection cn = null;
        ResultSet res = null;
        PreparedStatement ps = null;
        public ResultSet find(String s){
            try{
                cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
                ps = cn.prepareStatement("Select * from masterlist where booknumber = ?");
                ps.setString(1, s);
                res = ps.executeQuery();
                }      
                catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            return res;
        }
    }
   
    
    
    
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel bookno;
    private javax.swing.JButton borrow;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lang;
    private javax.swing.JLabel letter;
    private javax.swing.JTable library;
    private javax.swing.JPanel magic;
    private javax.swing.JTable magictable;
    private javax.swing.JLabel pub;
    private javax.swing.JLabel stud_bookno;
    private javax.swing.JButton stud_liba;
    private javax.swing.JButton stud_liba10;
    private javax.swing.JButton stud_liba11;
    private javax.swing.JButton stud_liba12;
    private javax.swing.JButton stud_liba13;
    private javax.swing.JButton stud_liba14;
    private javax.swing.JButton stud_liba15;
    private javax.swing.JButton stud_liba16;
    private javax.swing.JButton stud_liba17;
    private javax.swing.JButton stud_liba18;
    private javax.swing.JButton stud_liba19;
    private javax.swing.JButton stud_liba2;
    private javax.swing.JButton stud_liba20;
    private javax.swing.JButton stud_liba21;
    private javax.swing.JButton stud_liba22;
    private javax.swing.JButton stud_liba23;
    private javax.swing.JButton stud_liba24;
    private javax.swing.JButton stud_liba25;
    private javax.swing.JButton stud_liba26;
    private javax.swing.JButton stud_liba3;
    private javax.swing.JButton stud_liba4;
    private javax.swing.JButton stud_liba5;
    private javax.swing.JButton stud_liba6;
    private javax.swing.JButton stud_liba7;
    private javax.swing.JButton stud_liba8;
    private javax.swing.JButton stud_liba9;
    private javax.swing.JLabel stud_libauthor;
    private javax.swing.JLabel stud_liblang;
    private javax.swing.JLabel stud_libpub;
    private javax.swing.JLabel stud_libsubtitle;
    private javax.swing.JButton stud_libview;
    private javax.swing.JButton stud_logout;
    private javax.swing.JLabel stud_title;
    private javax.swing.JLabel sub;
    private javax.swing.JLabel text;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
