import java.awt.Frame;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class view extends javax.swing.JFrame{
      Connection cn;
      PreparedStatement ps;
      ResultSet res;
      String sort;
    /**
     * Creates new form login
     */
    public view(){
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        admin_addbtn = new javax.swing.JButton();
        admin_homebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin_delbtn = new javax.swing.JButton();
        admin_masterbtn = new javax.swing.JButton();
        c = new javax.swing.JButton();
        b = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        s = new javax.swing.JButton();
        admin_reqbtn4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        masterlist = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        errortitle = new javax.swing.JLabel();
        errorsubtitle = new javax.swing.JLabel();
        errorauthor = new javax.swing.JLabel();
        errorpub = new javax.swing.JLabel();
        errorlang = new javax.swing.JLabel();
        errormsg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sortby = new javax.swing.JComboBox();
        admin_editcancel = new javax.swing.JButton();
        admin_editsave = new javax.swing.JButton();
        admin_editlang = new javax.swing.JComboBox();
        admin_editpublisher = new javax.swing.JTextField();
        admin_editauthor = new javax.swing.JTextField();
        admin_editsubtitle = new javax.swing.JTextField();
        admin_viewtitle = new javax.swing.JTextField();
        bookno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        admin_editbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setBackground(new java.awt.Color(102, 102, 0));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 110, 30));

        admin_addbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_addbtn.setText("ADD BOOK");
        admin_addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, 50));

        admin_homebtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_homebtn.setText("HOME");
        admin_homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_homebtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 50));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrator Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 630, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\admintitle.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 110));

        admin_delbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_delbtn.setText("DELETE BOOK");
        admin_delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_delbtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_delbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 170, 50));

        admin_masterbtn.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_masterbtn.setText("MASTERLIST");
        admin_masterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_masterbtnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_masterbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 170, 50));

        c.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        c.setText("COUNTER");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 170, 50));

        b.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        b.setText("BOOK MONITOR");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 170, 50));

        edit.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        edit.setText("EDIT BOOK");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, 50));

        s.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        s.setText("STUDENT INFO");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 170, 50));

        admin_reqbtn4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        admin_reqbtn4.setText("REQUESTS");
        admin_reqbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_reqbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(admin_reqbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 170, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masterlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookNo", "Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masterlist.setGridColor(new java.awt.Color(255, 255, 255));
        masterlist.setShowHorizontalLines(false);
        masterlist.setShowVerticalLines(false);
        masterlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(masterlist);
        if (masterlist.getColumnModel().getColumnCount() > 0) {
            masterlist.getColumnModel().getColumn(0).setResizable(false);
            masterlist.getColumnModel().getColumn(0).setPreferredWidth(70);
            masterlist.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 320, 290));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("TITLE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        errortitle.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errortitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 10, -1));

        errorsubtitle.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorsubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 10, -1));

        errorauthor.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 10, -1));

        errorpub.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 10, -1));

        errorlang.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorlang, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 10, -1));

        errormsg.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errormsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("LANGUAGE:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("PUBLISHER:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("SUBTITLE:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("AUTHOR:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("BOOKNO:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Sort by");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        sortby.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sortby.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TITLE", "BOOKNO" }));
        sortby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortbyActionPerformed(evt);
            }
        });
        jPanel1.add(sortby, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 90, 30));

        admin_editcancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin_editcancel.setText("CANCEL");
        admin_editcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_editcancelActionPerformed(evt);
            }
        });
        jPanel1.add(admin_editcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 110, 50));

        admin_editsave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin_editsave.setText("SAVE");
        admin_editsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_editsaveActionPerformed(evt);
            }
        });
        jPanel1.add(admin_editsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 110, 50));

        admin_editlang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "English", "Filipino" }));
        admin_editlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_editlangActionPerformed(evt);
            }
        });
        jPanel1.add(admin_editlang, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 130, -1));

        admin_editpublisher.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        admin_editpublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_editpublisherActionPerformed(evt);
            }
        });
        jPanel1.add(admin_editpublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 260, -1));

        admin_editauthor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(admin_editauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 260, -1));

        admin_editsubtitle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(admin_editsubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 260, -1));

        admin_viewtitle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(admin_viewtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 260, -1));

        bookno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(bookno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel6.setText("Edit Book");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        admin_editbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admin_editbtn.setText("EDIT");
        admin_editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_editbtnActionPerformed(evt);
            }
        });
        jPanel1.add(admin_editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 110, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\LMS\\src\\whitebg.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 980, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admininnerbg.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1080, 620));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sony\\Desktop\\CCS\\Systems\\Backgrounds\\adminbg.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1300, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()|Frame.MAXIMIZED_BOTH);
        sort= "title";
        fetch();
    }//GEN-LAST:event_formWindowOpened

    private void admin_addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_addbtnActionPerformed
        add a = new add();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_addbtnActionPerformed

    private void admin_homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_homebtnActionPerformed
        admin a = new admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_homebtnActionPerformed

    private void masterlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterlistMouseClicked
 
        DefaultTableModel model = (DefaultTableModel)masterlist.getModel();
        int selectedRowIndex = masterlist.getSelectedRow();
        
        try{
        bookno.setText(model.getValueAt(selectedRowIndex, 0).toString());

        }
        catch(Exception e){
            
        }
         Function f = new Function();
        ResultSet res = null;
        res = f.find(bookno.getText());
        try{
            if(res.next()){
                admin_viewtitle.setText(res.getString("title"));
                admin_viewtitle.setEnabled(false);
                admin_editsubtitle.setText(res.getString("subtitle"));
                admin_editsubtitle.setEnabled(false);
                admin_editauthor.setText(res.getString("author"));
                admin_editauthor.setEnabled(false);
                admin_editpublisher.setText(res.getString("publisher"));
                admin_editpublisher.setEnabled(false);
                admin_editlang.setSelectedItem(res.getString("language"));
                admin_editlang.setEnabled(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Select one you wish to view details");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
      
    }//GEN-LAST:event_masterlistMouseClicked
   public class Function{
        Connection cn = null;
        ResultSet res = null;
        PreparedStatement ps = null;
        public ResultSet find(String s){
            try{
                cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
                ps = cn.prepareStatement("Select * from masterlist where booknumber = ?");
                ps.setString(1, s);
                res = ps.executeQuery();
                }      
                catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            return res;
        }
    }
    private void admin_editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_editbtnActionPerformed
       admin_viewtitle.setEnabled(true);
       admin_editsubtitle.setEnabled(true);
       admin_editauthor.setEnabled(true);
       admin_editpublisher.setEnabled(true);
       admin_editlang.setEnabled(true);
       
    }//GEN-LAST:event_admin_editbtnActionPerformed

    private void admin_masterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_masterbtnActionPerformed
        masterlist a = new masterlist();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_masterbtnActionPerformed

    private void admin_delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_delbtnActionPerformed
        delete a = new delete();
       a.setVisible(true);
       dispose();
    }//GEN-LAST:event_admin_delbtnActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
       counter a = new counter();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_cActionPerformed

    private void admin_editpublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_editpublisherActionPerformed
        
    }//GEN-LAST:event_admin_editpublisherActionPerformed

    private void admin_editlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_editlangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_editlangActionPerformed

    private void admin_editcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_editcancelActionPerformed
        admin a = new admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_editcancelActionPerformed

    private void admin_editsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_editsaveActionPerformed
        cn=sql.myConnection();
        String name = admin_editauthor.getText().toString();
        try{
          
            if(admin_viewtitle.getText().isEmpty()){
                errormsg.setText("Please Fill-up this Information.");
                errortitle.setText("*");
            } else{
                
                errortitle.setText("");
            }
             if(admin_editsubtitle.getText().isEmpty()){
                errormsg.setText("Please Fill-up this Information.");
                errorsubtitle.setText("*");
            } else{
                
                errorsubtitle.setText("");
            }
              if(admin_editauthor.getText().isEmpty()){
                errormsg.setText("Please Fill-up this Information.");
                errorauthor.setText("*");
              }  
             else{
                errorauthor.setText("");
            } 

              
               if(admin_editpublisher.getText().isEmpty()){
                errormsg.setText("Please Fill-up this Information.");
                errorpub.setText("*");
            } else{
                
                errorpub.setText("");
            }
               if(admin_editlang.getSelectedItem() == " "){
                errormsg.setText("Please Fill-up this information.");
                errorlang.setText("*");
            } else{
                
                errorlang.setText("");
            }
               if(errortitle.getText().isEmpty() & errorsubtitle.getText().isEmpty() & errorauthor.getText().isEmpty()& errorpub.getText().isEmpty() & errorlang.getText().isEmpty()){
                   errormsg.setText("");
               }
                if(!name.matches("^[a-zA-Z ]+")){
                   errormsg.setText("Please Fill-up with correct information.");
                   errorauthor.setText("*");
               }
                 if(errormsg.getText().isEmpty()){
                     String ins="UPDATE masterlist set title=?, subtitle=?, author=?, publisher=?, language=? where booknumber="+bookno.getText()+"";
                     ps=cn.prepareStatement(ins);            
                     ps.setString(1, admin_viewtitle.getText());           
                     ps.setString(2, admin_editsubtitle.getText());
                     ps.setString(3, admin_editauthor.getText());
                     ps.setString(4, admin_editpublisher.getText());
                     String lang=admin_editlang.getSelectedItem().toString();
                     ps.setString(5, lang);
                     ps.executeUpdate();
 
                     JOptionPane.showMessageDialog(null, "Successful!");
                     bookno.setText("");
                     admin_viewtitle.setText("");
                     admin_editsubtitle.setText("");
                     admin_editauthor.setText("");
                     admin_editpublisher.setText("");
                     admin_editlang.setSelectedItem(" ");
                 }
        
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_admin_editsaveActionPerformed

    private void sortbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortbyActionPerformed
        if(sortby.getSelectedItem() == "TITLE"){
            sort = "title";
            bookno.setText("");
            admin_viewtitle.setText("");
            admin_editsubtitle.setText("");
            admin_editauthor.setText("");
            admin_editpublisher.setText("");
            admin_editlang.setSelectedItem(" ");
        }
        if(sortby.getSelectedItem() == "BOOKNO"){
            bookno.setText("");
            sort = "booknumber";
            admin_viewtitle.setText("");
            admin_editsubtitle.setText("");
            admin_editauthor.setText("");
            admin_editpublisher.setText("");
            admin_editlang.setSelectedItem(" ");
        }
        fetch();
        
    }//GEN-LAST:event_sortbyActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
       monitor a = new monitor();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_bActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        view a = new view();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_editActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
       admininfo a = new admininfo();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_sActionPerformed

    private void admin_reqbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_reqbtn4ActionPerformed
        adminstatus a = new adminstatus();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_reqbtn4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login a = new login();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void fetch(){
        try{
            cn=DriverManager.getConnection("jdbc:mysql://localhost/lms","root","");
            String q = "Select booknumber as 'BookNo' , title as 'Title' from masterlist order by " + sort + " asc";
            
            ps = cn.prepareStatement(q);
            res=ps.executeQuery();

            masterlist.setModel(DbUtils.resultSetToTableModel(res));
        } 
        catch(Exception e){
           
        }
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_addbtn;
    private javax.swing.JButton admin_delbtn;
    private javax.swing.JTextField admin_editauthor;
    private javax.swing.JButton admin_editbtn;
    private javax.swing.JButton admin_editcancel;
    private javax.swing.JComboBox admin_editlang;
    private javax.swing.JTextField admin_editpublisher;
    private javax.swing.JButton admin_editsave;
    private javax.swing.JTextField admin_editsubtitle;
    private javax.swing.JButton admin_homebtn;
    private javax.swing.JButton admin_masterbtn;
    private javax.swing.JButton admin_reqbtn4;
    private javax.swing.JTextField admin_viewtitle;
    private javax.swing.JButton b;
    private javax.swing.JLabel bookno;
    private javax.swing.JButton c;
    private javax.swing.JButton edit;
    private javax.swing.JLabel errorauthor;
    private javax.swing.JLabel errorlang;
    private javax.swing.JLabel errormsg;
    private javax.swing.JLabel errorpub;
    private javax.swing.JLabel errorsubtitle;
    private javax.swing.JLabel errortitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable masterlist;
    private javax.swing.JButton s;
    private javax.swing.JComboBox sortby;
    // End of variables declaration//GEN-END:variables
}
